export const Constants = {
    code: "Số hiệu",
    item: "Mặt hàng",
    quantity:"Số lượng",
    unit_price: "Đơn giá",
    total_price:"Tổng giá",
    cash:"Tiền mặt",
    transfer :"Chuyển khoản",
    bank_name: "Ngân hàng",
    bank_account_number: "Số tài khoản",
    bank_account_owner : "Chủ tài khoản",
    amount_money: "Số tiền",
    transfer_content: "Nội dung",
    currency_unit: "VND",
    liters:"L",
    note1: 'Quét mã QR bằng ứng dụng ngân hàng ',
    note2: 'hoặc ví điện tử để thanh toán',
    note3: 'Chưa thanh toán thành công.',
    note4:'Vui lòng thanh toán trước khi thực hiện.'
}